### ISSUE TITLE
coturn metric: malformed response

### ISSUE THREAD

**Issue by njam** [cargomedia/bipbip#153]
```
E, [2016-06-09T13:07:18.570415 #24760] ERROR -- coturn janus2.example.com::coturn::localhost: Cannot prepare metrics for malformed response: `TURN Server
Coturn-4.5.0.3 'dan Eider'

Type '?' for help
> `. Error: `undefined method `[]' for nil:NilClass`
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/plugin/coturn.rb:23:in `rescue in monitor'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/plugin/coturn.rb:16:in `monitor'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/plugin.rb:80:in `run_measurement'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/plugin.rb:39:in `block (2 levels) in run'
 /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/plugin.rb:38:in `block in run'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/plugin.rb:36:in `loop'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/plugin.rb:36:in `run'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.21/lib/bipbip/agent.rb:59:in `block in start_plugin'
```

@kris-lab Is this expected?

**Comment by kris-lab** [comment]
Yes, this is expected. We decided to throw this error here https://github.com/cargomedia/bipbip/pull/147

Sometime `coturn` doesn't response with properly.

**Comment by njam** [comment]
true, my bad
